apiVersion: v1
kind: Service
metadata:
  name: nodedsl2
  labels:
    app: nodedsl2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodedsl2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodedsl-deployment2
spec:
  selector:
    matchLabels:
      app: nodedsl2
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nodedsl2
        version: v1
    spec:
      containers:
      - name: nodedsl2
        image: fra.ocir.io/wolf359/aldermore/nodedscd:v1.0
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
